/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HMS_Package;

import static HMS_Package.Patient_Register.isValidEmail;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Onkar
 */
public class Doctor_Register extends javax.swing.JFrame {

    /**
     * Creates new form Doctor_Register
     */
    public Doctor_Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        D1 = new javax.swing.JTextField();
        D2 = new javax.swing.JTextField();
        D3 = new javax.swing.JTextField();
        D5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        R2 = new javax.swing.JRadioButton();
        R1 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        D6 = new javax.swing.JTextField();
        P1 = new javax.swing.JPasswordField();
        D = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        D7 = new javax.swing.JTextField();
        D4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Doctor-Register");
        setBounds(new java.awt.Rectangle(100, 30, 1200, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Schedule");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 60, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Age");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Doctor_Id");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Langauge Spoken");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Qulification");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, -1, -1));

        D1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        D1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        D1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D1ActionPerformed(evt);
            }
        });
        getContentPane().add(D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 300, 30));

        D2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        D2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 300, 30));

        D3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        D3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(D3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 300, 30));

        D5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        D5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(D5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, 300, 30));

        jButton1.setBackground(new java.awt.Color(63, 123, 191));
        jButton1.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancle");
        jButton1.setName("Cancle_btn"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 620, -1, 50));

        jButton2.setBackground(new java.awt.Color(63, 123, 191));
        jButton2.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 620, -1, 50));

        jButton3.setBackground(new java.awt.Color(63, 123, 191));
        jButton3.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 620, -1, 50));

        jButton4.setBackground(new java.awt.Color(63, 123, 191));
        jButton4.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 620, -1, 50));

        R2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        R2.setText("Female");
        getContentPane().add(R2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, -1, -1));

        R1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        R1.setText("Male");
        R1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1ActionPerformed(evt);
            }
        });
        getContentPane().add(R1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Email");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, -1, -1));

        D6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        D6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        D6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D6ActionPerformed(evt);
            }
        });
        getContentPane().add(D6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 530, 300, 30));

        P1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        P1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 570, 300, 30));

        D.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        D.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(D, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, 300, 30));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HMS_Package/Images/DoctorRegisterForm.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1170, -1));

        jButton5.setBackground(new java.awt.Color(63, 123, 191));
        jButton5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Do you have an account?Login");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 690, -1, -1));

        D7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        D7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        D7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D7ActionPerformed(evt);
            }
        });
        getContentPane().add(D7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 300, 30));

        D4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        D4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(D4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 300, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Gender");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Specilization");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HMS_Package/Images/HMSBackground1.jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Frame2 f2 = new Frame2();
        f2.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed
  private static final String EMAIL_REGEX = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
    
    public static boolean isValidEmail(String email){
       
        Pattern pattern = Pattern.compile(EMAIL_REGEX);
        Matcher matcher = pattern.matcher(email);
        return !matcher.matches();
    }
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
        String query,did,dname,age,gender,gender1,email,pass,quli,spe,lspo,sch;
        did =D1.getText();
        dname = D2.getText();
        age = D3.getText();
        quli = D4.getText();
        spe = D5.getText();
        email = D6.getText();
        pass = P1.getText();
        gender = R1.getText();
        gender1 = R2.getText();
        lspo = D7.getText();
        sch = D.getText();
        
     
     try{
       Connection cn = null;
       Statement st = null;
       Class.forName("com.mysql.cj.jdbc.Driver");
       cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/hms","root","o4n9k3a9r1");
       st = cn.createStatement();
        if(did.equals("")){
     JOptionPane.showMessageDialog(rootPane, "Please enter your id");
     }       
     else if(dname.equals("")){
          JOptionPane.showMessageDialog(rootPane, "Please enter your name");
     }
      else if(age.equals("")){
          JOptionPane.showMessageDialog(rootPane, "Please enter your age");
     }
      else if(quli.equals("") ){
          JOptionPane.showMessageDialog(rootPane, "Please enter your Qulification");
     }
      else if(spe.equals("")){
          JOptionPane.showMessageDialog(rootPane, "Please enter your specilization");
     }
      else if(email.equals("")){
          JOptionPane.showMessageDialog(rootPane, "Please enter your Email");
     }
      else if(pass.equals("")){
          JOptionPane.showMessageDialog(rootPane, "Please enter your password");
     }else if(isValidEmail(email)) {
            JOptionPane.showMessageDialog(rootPane, "is a Invalid email.");
           // System.out.println(email + " is a valid email.");
        }
      else{
          if(R1.isSelected() && R2.isSelected()){
//               query = "INSERT INTO `doctorregister`(`Doctor_id`, `DName`, `age`, `Gender`, `Email`, `password`, `qulification`, `spelization`)  "
//                      + "VALUES ('"+did+"','"+dname+"','"+age+"','"+gender+"','"+email+"','"+pass+"','"+quli+","+spe+"')";
//              //st.executeUpdate(query);
//              //cn.close();
//               System.out.println("Databse Connected!"+query);
//        this.dispose();
          JOptionPane.showMessageDialog(rootPane, "Please select one option in gender M/F");

          
         // d.setVisible(true);
          } else if(R2.isSelected()) {
               query = "INSERT INTO doctor (`D_id`, `DName`, `age`, `Gender`,`langaugeSpoke`, `Department`, `qulification`, `Schdule`, `Email`, `pass`)  "
                      + "VALUES ('"+did+"','"+dname+"','"+age+"','"+gender1+"','"+lspo+"','"+spe+"','"+quli+"','"+sch+"','"+email+"','"+pass+"')";
              st.executeUpdate(query);
              cn.close();
               //System.out.println("Databse Connected!"+query);
        this.dispose();
        Doctor d = new Doctor(did);
        d.setVisible(true);
           }else{
              
              query = "INSERT INTO doctor (`D_id`, `DName`, `age`, `Gender`,`langaugeSpoke`, `Department`, `qulification`, `Schdule`, `Email`, `pass`)  "
                      + "VALUES ('"+did+"','"+dname+"','"+age+"','"+gender+"','"+lspo+"','"+spe+"','"+quli+"','"+sch+"','"+email+"','"+pass+"')";
              st.executeUpdate(query);
              cn.close();
              // System.out.println("Databse Connected!"+query);
        this.dispose();
        Doctor d = new Doctor(did);
         d.setVisible(true);
          }
           
      }
     }catch(Exception ex){
       System.out.println("Error"+ex.getMessage());

     }
       
       

    }//GEN-LAST:event_jButton2ActionPerformed

    private void D1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D1ActionPerformed

    private void R1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          String query,did,dname,age,gender,gender1,email,pass,quli,spe;
        did =D1.getText();
        dname = D2.getText();
        age = D3.getText();
        quli = D.getText();
        spe = D5.getText();
        email = D6.getText();
        pass = P1.getText();
        gender = R1.getText();
        gender1 = R2.getText();

        
        Doctor d = new Doctor();
     
     try{
       Connection cn = null;
       Statement st = null;
       Class.forName("com.mysql.cj.jdbc.Driver");
       cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/hms","root","");
       st = cn.createStatement();
        if(did.equals("")){
     JOptionPane.showMessageDialog(rootPane, "Please enter your id");
     }       
     else if(dname.equals("")){
          JOptionPane.showMessageDialog(rootPane, "Please enter your name");
     }
      else if(age.equals("")){
          JOptionPane.showMessageDialog(rootPane, "Please enter your age");
     }
      else if(quli.equals("") ){
          JOptionPane.showMessageDialog(rootPane, "Please enter your Qulification");
     }
      else if(spe.equals("")){
          JOptionPane.showMessageDialog(rootPane, "Please enter your specilization");
     }
      else if(email.equals("")){
          JOptionPane.showMessageDialog(rootPane, "Please enter your Email");
     }
      else if(pass.equals("")){
          JOptionPane.showMessageDialog(rootPane, "Please enter your password");
     }
      else{
          if(R1.isSelected() && R2.isSelected()){
//               query = "INSERT INTO `doctorregister`(`Doctor_id`, `DName`, `age`, `Gender`, `Email`, `password`, `qulification`, `spelization`)  "
//                      + "VALUES ('"+did+"','"+dname+"','"+age+"','"+gender+"','"+email+"','"+pass+"','"+quli+","+spe+"')";
//              //st.executeUpdate(query);
//              //cn.close();
//               System.out.println("Databse Connected!"+query);
//        this.dispose();
          JOptionPane.showMessageDialog(rootPane, "Please select one option in gender M/F");

          
         // d.setVisible(true);
          } else if(R2.isSelected()) {
               query = "UPDATE `doctorregister` SET `DName`='"+dname+"',`age`='"+age+"',`Gender`='"+gender1+"',"
                       + "`Email`='"+email+"',`password`='"+pass+"',`qulification`='"+quli+"',`Department`='"+spe+"' WHERE `Doctor_id`='"+did+"'";
              st.executeUpdate(query);
              cn.close();
               //System.out.println("Databse Connected!"+query);
        this.dispose();
          
          d.setVisible(true);
           }else{
              
              query = "UPDATE `doctorregister` SET `DName`='"+dname+"',`age`='"+age+"',`Gender`='"+gender+"',"
                       + "`Email`='"+email+"',`password`='"+pass+"',`qulification`='"+quli+"',`Department`='"+spe+"' WHERE `Doctor_id`='"+did+"'";
              st.executeUpdate(query);
              cn.close();
               //System.out.println("Databse Connected!"+query);
        this.dispose();
         d.setVisible(true);
          }
           
      }
     }catch(Exception ex){
       System.out.println("Error"+ex.getMessage());

     }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here
            Doctor_Login Dl= new Doctor_Login();
        Dl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void D7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D7ActionPerformed

    private void D6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          String D_id;
        D_id = D1.getText();
         try{
       Connection cn = null;
       Statement st = null;
       Class.forName("com.mysql.cj.jdbc.Driver");
       cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/hms","root","o4n9k3a9r1");
       st = cn.createStatement();
       
       
         
        if(D_id.equals("")){
        JOptionPane.showMessageDialog(rootPane, "Please enter your id required and delete");
        }else{
          String  query = "DELETE FROM doctor WHERE `D_id`='"+D_id+"'";
              st.executeUpdate(query);
              cn.close();
                      JOptionPane.showMessageDialog(rootPane, "Your data was delete!");
                      Frame2 f2 = new Frame2();
        f2.setVisible(true);
        this.dispose(); 

               //System.out.println("Databse Connected!"+query);
        }
          }catch(Exception ex){
             System.out.println("Error"+ex.getMessage());

     }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor_Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField D;
    private javax.swing.JTextField D1;
    private javax.swing.JTextField D2;
    private javax.swing.JTextField D3;
    private javax.swing.JTextField D4;
    private javax.swing.JTextField D5;
    private javax.swing.JTextField D6;
    private javax.swing.JTextField D7;
    private javax.swing.JPasswordField P1;
    private javax.swing.JRadioButton R1;
    private javax.swing.JRadioButton R2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
