/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HMS_Package;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Onkar
 */
public class Patient_Register extends javax.swing.JFrame {

    private String p_id;

    /**
     * Creates new form Patient_Register
     */
    public Patient_Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        P1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        P5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        P2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        R2 = new javax.swing.JRadioButton();
        R1 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        P3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        P4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        P6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Pass1 = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        P7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patient-Register");
        setBounds(new java.awt.Rectangle(100, 30, 1200, 750));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Patient_Id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, 20));

        P1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        P1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        P1.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 300, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, 20));

        P5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        P5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        P5.setPreferredSize(new java.awt.Dimension(200, 30));
        P5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P5ActionPerformed(evt);
            }
        });
        getContentPane().add(P5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 300, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("DOB");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, 20));

        P2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        P2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        P2.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 300, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Mob no");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, -1, 20));

        R2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        R2.setText("Female");
        R2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R2ActionPerformed(evt);
            }
        });
        getContentPane().add(R2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, -1, -1));

        R1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        R1.setText("Male");
        getContentPane().add(R1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Blood-Group");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, 20));

        P3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        P3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        P3.setPreferredSize(new java.awt.Dimension(200, 30));
        P3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P3ActionPerformed(evt);
            }
        });
        getContentPane().add(P3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 300, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, -1, 20));

        P4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        P4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        P4.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(P4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 300, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, 20));

        P6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        P6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        P6.setMinimumSize(new java.awt.Dimension(200, 30));
        getContentPane().add(P6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 300, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, -1, 20));

        jButton3.setBackground(new java.awt.Color(63, 123, 191));
        jButton3.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Cancle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 510, -1, 50));

        Pass1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Pass1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Pass1.setMinimumSize(new java.awt.Dimension(200, 30));
        Pass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pass1ActionPerformed(evt);
            }
        });
        getContentPane().add(Pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 300, 30));

        jButton4.setBackground(new java.awt.Color(63, 123, 191));
        jButton4.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Register");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, -1, 50));

        jButton5.setBackground(new java.awt.Color(63, 123, 191));
        jButton5.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, -1, 50));

        jButton6.setBackground(new java.awt.Color(63, 123, 191));
        jButton6.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, -1, 50));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        jLabel9.setBackground(new java.awt.Color(63, 123, 191));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HMS_Package/Images/PatientRegisterForm.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1170, -1));

        jButton7.setBackground(new java.awt.Color(63, 123, 191));
        jButton7.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Do you have an account?Login");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 590, -1, -1));

        P7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        P7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        P7.setMinimumSize(new java.awt.Dimension(200, 30));
        P7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P7ActionPerformed(evt);
            }
        });
        getContentPane().add(P7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 300, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Gender");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HMS_Package/Images/HMSBackground1.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void P5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P5ActionPerformed

    private void R2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R2ActionPerformed

    private void Pass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pass1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         Frame2 f2 = new Frame2();
        f2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         String patient_id;
        patient_id = P1.getText();
         try{
       Connection cn = null;
       Statement st = null;
       Class.forName("com.mysql.cj.jdbc.Driver");
       cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/hms","root","o4n9k3a9r1");
       st = cn.createStatement();
       
       
         
        if(patient_id.equals("")){
        JOptionPane.showMessageDialog(rootPane, "Please enter your id required and delete");
        }else{
          String  query = "DELETE FROM patient WHERE `p_id`='"+patient_id+"'";
              st.executeUpdate(query);
              cn.close();
                      JOptionPane.showMessageDialog(rootPane, "Your data was delete!");
                      Frame2 f2 = new Frame2();
        f2.setVisible(true);
        this.dispose(); 

               //System.out.println("Databse Connected!"+query);
        }
          }catch(Exception ex){
             System.out.println("Error"+ex.getMessage());

     }
    
    

    }//GEN-LAST:event_jButton6ActionPerformed
   private static final String EMAIL_REGEX = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
   private static final String MOBILE_NUMBER_REGEX = "^[0-9]{10}$";

    
    public static boolean isValidEmail(String email){
       
        Pattern pattern = Pattern.compile(EMAIL_REGEX);
        Matcher matcher = pattern.matcher(email);
        return !matcher.matches();
    }
      public static boolean isValidMobileNumber(String mobileNumber) {
        Pattern pattern = Pattern.compile(MOBILE_NUMBER_REGEX);
        Matcher matcher = pattern.matcher(mobileNumber);
        return !matcher.matches();
    }
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String p_id,name,bg,address,dob,gender,gender1,email ,pass,query,mobno;
        p_id = P1.getText();
        name = P2.getText();
        bg = P3.getText();
        address =P4.getText();
        dob = P5.getText();
        email = P6.getText();
        mobno = P7.getText();
        pass = Pass1.getText();
        gender =R1.getText();
        gender1 =R2.getText();
        
              
       
     try{
       Connection cn = null;
       Statement st = null;
       Class.forName("com.mysql.cj.jdbc.Driver");
       cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/hms","root","o4n9k3a9r1");
       st = cn.createStatement();
       
         
        if(p_id.equals("")){
        JOptionPane.showMessageDialog(rootPane, "Please enter your id");
        }
        else if(name.equals("")){
        JOptionPane.showMessageDialog(rootPane, "Please enter your name");
        }
        else if(bg.equals("")){
        JOptionPane.showMessageDialog(rootPane, "Please enter your blood-group");
        }
        else if(address.equals("")){
        JOptionPane.showMessageDialog(rootPane, "Please enter your address");
        }
        else if(dob.equals("")){
        JOptionPane.showMessageDialog(rootPane, "Please enter your DOB");
        }
        else if(email.equals("")){
        JOptionPane.showMessageDialog(rootPane, "Please enter your Email");
        }
        else if(pass.equals("")){
        JOptionPane.showMessageDialog(rootPane, "Please enter your password");
        } else  if (isValidEmail(email)) {
            JOptionPane.showMessageDialog(rootPane, "is a Invalid email.");
           // System.out.println(email + " is a valid email.");
        }
        else if (isValidMobileNumber(mobno)) {
                        JOptionPane.showMessageDialog(rootPane, "is a Invalid mobile number.");

                //System.out.println(mobno + " is a Invalid mobile number.");
            }
        else{
            //System.out.println(email + " is an invalid email.");

            if(R1.isSelected() && R2.isSelected()){
                           JOptionPane.showMessageDialog(rootPane, "Please select one option in gender M/F");
        
            }else if(R1.isSelected()){
                 query = "INSERT INTO patient(`p_id`, `Fname`, `Blood_Group`, `address`, `dob`, `gender`,`mob`, `email`, `password`) "
                                  + "VALUES ('"+p_id+"','"+name+"','"+bg+"','"+address+"','"+dob+"','"+gender+"','"+mobno+"','"+email+"','"+pass+"')";
              st.executeUpdate(query);
              cn.close();
               //System.out.println("Databse Connected!"+query);
                 Patient p = new Patient(p_id);
               p.setVisible(true);
            this.dispose();
            }else{
            query = "INSERT INTO patient(`p_id`, `Fname`, `Blood_Group`, `address`, `dob`, `gender`,  `mob`,`email`, `password`) "
                                  + "VALUES ('"+p_id+"','"+name+"','"+bg+"','"+address+"','"+dob+"','"+gender1+"','"+mobno+"','"+email+"','"+pass+"')";
              st.executeUpdate(query);
              cn.close();
               //System.out.println("Databse Connected!"+query);
                       Patient p = new Patient(p_id);

               p.setVisible(true);
            this.dispose();
            }
            

        }
       
     }catch(Exception ex){
       System.out.println("Error"+ex.getMessage());

     }
     
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here
               Patient_Login Pl = new Patient_Login();
        Pl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void P3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
      String p_id,name,bg,address,dob,gender,gender1,email ,pass,query,mobno;
        p_id = P1.getText();
        name = P2.getText();
        bg = P3.getText();
        address =P4.getText();
        dob = P5.getText();
        email = P6.getText();
        mobno = P7.getText();
        pass = Pass1.getText();
        gender =R1.getText();
        gender1 =R2.getText();
       Patient p = new Patient(p_id);    
     try{
       Connection cn = null;
       Statement st = null;
       Class.forName("com.mysql.cj.jdbc.Driver");
       cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/hms","root","o4n9k3a9r1");
       st = cn.createStatement();
        if(p_id.equals("")){
        JOptionPane.showMessageDialog(rootPane, "Please enter your id");
        }
        else if(name.equals("")){
        JOptionPane.showMessageDialog(rootPane, "Please enter your name");
        }
        else if(bg.equals("")){
        JOptionPane.showMessageDialog(rootPane, "Please enter your blood-group");
        }
        else if(address.equals("")){
        JOptionPane.showMessageDialog(rootPane, "Please enter your address");
        }
        else if(dob.equals("")){
        JOptionPane.showMessageDialog(rootPane, "Please enter your DOB");
        }
        else if(email.equals("")){
        JOptionPane.showMessageDialog(rootPane, "Please enter your Email");
        }
        else if(pass.equals("")){
        JOptionPane.showMessageDialog(rootPane, "Please enter your password");
        }else{
            if(R1.isSelected() && R2.isSelected()){
                           JOptionPane.showMessageDialog(rootPane, "Please select one option in gender M/F");
        
            }else if(R1.isSelected()){
                 query = "UPDATE patient SET `Fname`='"+name+"',`Blood_Group`='"+bg+"',`address`='"+address+"',"
                         + "`dob`='"+dob+"',`gender`='"+gender+"',`mob`='"+mobno+"',`email`='"+email+"',`password`='"+pass+"' WHERE `p_id`='"+p_id+"'";
              st.executeUpdate(query);
              cn.close();
               //System.out.println("Databse Connected!"+query);
               p.setVisible(true);
            this.dispose();
            }else{
            query = "UPDATE `patientregister` SET `name`='"+name+"',`Blood_Group`='"+bg+"',`address`='"+address+"',"
                         + "`dob`='"+dob+"',`gender`='"+gender1+"',`mob`='"+mobno+"',`email`='"+email+"',`password`='"+pass+"' WHERE `Patient_id`='"+p_id+"'";
              st.executeUpdate(query);
              cn.close();
               //System.out.println("Databse Connected!"+query);
               p.setVisible(true);
            this.dispose();
            }
            

        }
       
     }catch(Exception ex){
            System.out.println("Error"+ex.getMessage());

     }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void P7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient_Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField P1;
    private javax.swing.JTextField P2;
    private javax.swing.JTextField P3;
    private javax.swing.JTextField P4;
    private javax.swing.JTextField P5;
    private javax.swing.JTextField P6;
    private javax.swing.JTextField P7;
    private javax.swing.JPasswordField Pass1;
    private javax.swing.JRadioButton R1;
    private javax.swing.JRadioButton R2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
